# Generated by Django 3.1.7 on 2021-05-05 17:58

from django.db import migrations, models
import login.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('roll_no', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True, validators=[login.models.valid_email])),
                ('phone', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='Male', max_length=255)),
                ('Course', models.CharField(choices=[('copc', 'COPC'), ('cose', 'COSE'), ('enc', 'ENC'), ('coe', 'COE'), ('ele', 'ELE'), ('ece', 'ECE'), ('mec', 'MEC'), ('che', 'CHE')], default='COPC', max_length=255)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=20)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
            ],
            options={
                'db_table': 'STUDENT',
            },
        ),
    ]
