# Generated by Django 3.1.7 on 2021-05-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20210512_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='login.customuser'),
        ),
    ]
