# Generated by Django 3.1.7 on 2021-05-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210513_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'warden',
            },
        ),
    ]
