# Generated by Django 3.1.7 on 2021-05-14 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_user_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='student_no',
        ),
    ]
