# Generated by Django 3.1.7 on 2021-05-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20210514_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='student_no',
        ),
    ]
