# Generated by Django 3.1.7 on 2021-05-15 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20210515_0011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='id',
            new_name='warden_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_no',
        ),
        migrations.AddField(
            model_name='customuser',
            name='warden_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
