# Generated by Django 3.1.7 on 2021-05-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_auto_20210515_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='warden_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='login.user'),
        ),
    ]
