# Generated by Django 3.1.7 on 2021-05-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_auto_20210515_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='student_email',
            field=models.EmailField(max_length=255),
        ),
    ]
