# Generated by Django 3.1.7 on 2021-05-17 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20210516_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date_of_entry',
            field=models.DateField(),
        ),
    ]
